version: '3'

services:
  mongo:
    image: mongo:3.6
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - ./volume/mongo/:/data/db
    networks:
      - clean-api-network
  node:
    image: node:12
    working_dir: /usr/src/app
    ports: 
      - "5050:5050"
    volumes:
      - ./dist:/usr/src/app/dist/
      - ./volume/node:/usr/src/app/node_modules/
      - ./package.json:/usr/src/app/package.json
    links:
      - "mongo"
    networks:
      - clean-api-network
    command: "npm run docker"
networks: 
    clean-api-network:
      driver: bridge