version: '3'

services:
  mongo:
    image: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - ./volume/mongo/:/data/db
    networks:
      - clean-api-network
  node:
    image: node:12
    ports: 
      - "5050:5050"
    volumes:
      - ./:/usr/src/clean-node-api
    working_dir: /usr/src/clean-node-api
    command: "npm run docker"
    links:
      - "mongo"
    networks:
      - clean-api-network
networks: 
    clean-api-network:
      driver: bridge