version: '3'

services:
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./volume/mongo/:/data/db
    networks:
      - clean-api-network
  node:
    image: node:12
    restart: always
    working_dir: /usr/src/app
    ports: 
      - "5050:5050"
      - "9222:9222"
    volumes:
      - ./dist/:/usr/src/app/dist/
      - ./package.json:/usr/src/app/package.json
    links:
      - "mongo"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    networks:
      - clean-api-network
    command: bash -c "npm install -g nodemon && npm install --only=prod && npm run debug"
networks: 
    clean-api-network:
      driver: bridge